language: rust
cache: 
  directories:
    - $HOME/.rustup
    - $HOME/.cargo
sudo: false

before_install:
  - rustup update
  - rustup target add wasm32-unknown-unknown
  - rustup component add rustfmt
  - cargo update

jobs:
  include:
    - stage: fomatted?
      script: cargo fmt -- --check
    - stage: check
      script: cargo check --target=wasm32-unknown-unknown
    - stage: test
      script: cargo test --all

notifications:
  email:
    on_success: never