[[server]]
genre = "server"
protocol = "rtmp"
code = "h264"
host = "0.0.0.0"
port = 1935


[[server]]
genre = "push"
protocol = "websocket"
code = "fmp4"
host = "0.0.0.0"
port = 8080


[pool]
bytes = 10