{
    "version": "3",
    "services": {
        "turn": {
            "build": {
                "context": ".",
                "dockerfile": "./bin/turn/Dockerfile"
            },
            "depends_on": [
                "nats"
            ],
            "restart": "unless-stopped",
            "volumes": [
                "./target:/usr/local/src/target"
            ],
            "environment": [
                "TURN_NATS=nats:4222",
                "RUST_BACKTRACE=1"
            ],
            "deploy": {
                "replicas": 1
            },
            "ports": [
                "3478:3478/udp"
            ]
        },
        "nats": {
            "image": "nats:latest",
            "restart": "unless-stopped",
            "deploy": {
                "replicas": 1
            },
            "ports": [
                "4222:4222"
            ]
        }
    }
}
