[package]
name = "faster-stun"
version = "1.0.0"
edition = "2021"
authors = ["Mr.Panda <xivistudios@gmail.com>"]
description = "Fast and zero-cost stun message decoder and encoder."
readme = "../README.md"
homepage = "https://github.com/colourful-rtc/turn-rs"
repository = "https://github.com/colourful-rtc/turn-rs"
license = "GPL-2.0-or-later"
keywords = [
    "stun",
    "webrtc",
    "turn"
]

categories = [
    "parsing",
    "network-programming"
]

[dependencies]
bytes = "1"
anyhow = "1.0"
num_enum = "0.5.0"
md5 = "0.7.0"
hmac = "0.10.1"
sha-1 = "0.9.2"
crc = "1.8.1"

[dev-dependencies.criterion]
features = ["html_reports"]
version = "0.4"

[[bench]]
name = "benchmark"
harness = false
