[package]
name = "testing"
version = "0.1.0"
authors = ["Mr.Panda <xivistudios@gmail.com>"]
edition = "2018"

[dependencies.stun]
path = "../lib/stun"

[dependencies.tokio]
version = "0.2"
features = ["full"]
