[package]
name = "turn-server-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[workspace]

[dependencies]
turn-server = { path = "../", default-features = false }
bytes = "1"

[dev-dependencies]
proptest = "1.4"
